### ISSUE TITLE
More details for setup

### ISSUE THREAD

**Issue by Bouni** [robbiet480/cec-web#8]
Hi,
can you please provide more detailed what's necessary for setting up cece-web on a RaspberryPi?

I'm on a RaspberryPi 3B+ running the latest Raspbian Stretch Lite, Date: 2019-04-08 Kernel version: 4.14

I finally managed to build it but when I execute the binary I get an exception:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x637f8]

goroutine 17 [running, locked to thread]:
panic(0x5fabe0, 0x56870010)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
github.com/robbiet480/cec._Cfunc_GoString(0x88, 0x0, 0x0)
        ??:0 +0x28
github.com/robbiet480/cec.logMessageCallback(0x0, 0x88, 0x0, 0x2682058, 0x76e69a00, 0x5689af48)
        /home/pi/go/src/github.com/robbiet480/cec/callbacks.go:53 +0x5c
github.com/robbiet480/cec._cgoexpwrap_9f7a035b8d26_logMessageCallback(0x0, 0x88, 0x0, 0x2682058, 0x76e69a00, 0x1)
        ??:0 +0x44
```
I've installed **libcec** with `apt-get install libcec` which gave me **libcec (4.0.4.1~stretch)**

Any ideas whats the problem here?

**Comment by Markkuuss** [comment]
I have the exact same error.  Perhaps someone has already found a solution in the meantime?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x9d pc=0x13ccc]

goroutine 17 [running, locked to thread]:
github.com/robbiet480/cec._Cfunc_GoString(...)
        _cgo_gotypes.go:312
github.com/robbiet480/cec.logMessageCallback(0x0, 0x9d, 0x0, 0x11b8110, 0x76e1ea00, 0x0)
        /home/pi/go/src/github.com/robbiet480/cec/callbacks.go:53 +0x44
github.com/robbiet480/cec._cgoexpwrap_c2d9ffa8fa45_logMessageCallback(0x0, 0x9d, 0x0, 0x11b8110, 0x76e1ea00, 0x1)
        _cgo_gotypes.go:728 +0x3c
```
